# Update

# steps:
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '-t', '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/backend-repo/backend-image:${SHORT_SHA}', '.']

# - name: 'gcr.io/cloud-builders/docker'
#   args: ['push', '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/backend-repo/backend-image:${SHORT_SHA}']

# images:
# - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/backend-repo/backend-image:${SHORT_SHA}'

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'northamerica-northeast2-docker.pkg.dev/gcpapp-444503/backend-repo/backend-image:${SHORT_SHA}', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'northamerica-northeast2-docker.pkg.dev/gcpapp-444503/backend-repo/backend-image:${SHORT_SHA}']

images:
- 'northamerica-northeast2-docker.pkg.dev/gcpapp-444503/backend-repo/backend-image:${SHORT_SHA}'

options:
  default_logs_bucket_behavior: 'REGIONAL_USER_OWNED_BUCKET'

